### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by Naturalclar** [react-native-community/react-native-checkbox#34]
# Feature Request

Introducing typescript support for the repo.

## Why it is needed

With the increasing popularity in typescript, it would be nice to have typescript support or at least a type declaration for the repo.
Currently, this repo does not have a typescript definition in @types repo.
There are declaration files in `@types/react-native` that can be extracted to this repository.

## Possible implementation

I believe there are two ways to approach this.
- create an `index.d.ts` file, extracted from `@types/react-native`
- convert each js files into `.tsx` and rewrite the modules in typescript

Any thoughts?

**Comment by nicholaslee119** [comment]
Agree with that, and we should TypeScriptify the test files

**Comment by nicholaslee119** [comment]
https://github.com/react-native-community/react-native-checkbox/tree/typescript/main
↑　I made a new branch which name is `typescript/main` , let us work on it

**Comment by unnamed92** [comment]
Any progress so far?

**Comment by LanaIV** [comment]
Impossible to use this module on TS project, when this feature will be released?

**Comment by nicholaslee119** [comment]
0.4.0 was just released, it supports for TypeScript. please try it.

**Comment by irekrog** [comment]
@nicholaslee119 

I tried but 0.4.1 doesn't work with TypeScript.

`import CheckBox from '@react-native-community/checkbox';`

> Cannot find module '@react-native-community/checkbox' or its corresponding type declarations.

I think maybe this is problem with 
`  "types": "dist/CheckBox.d.ts"` in package.json library because this file doesn't exists

**Comment by BenoitSerrano** [comment]
Hey @nicholaslee119 :) Any update on the fix release date ? :)

**Comment by orihero** [comment]
6 months later ...
No update!???

**Comment by nicholaslee119** [comment]
v0.4.2 was released, Typescript support is fixed.
Thank you for your patience, Try it if there is any problem let us known, please

**Comment by flo5324** [comment]
Just installed v0.4.2 but getting the error `Unable to resolve path to module '@react-native-community/checkbox'`
Import works fine, but I cannot get autocompletion for this components' props.

**Comment by nicholaslee119** [comment]
> Just installed v0.4.2 but getting the error `Unable to resolve path to module '@react-native-community/checkbox'`
> Import works fine, but I cannot get autocompletion for this components' props.

Have you ever tried to restart your IDE?

**Comment by tamirla** [comment]
> > Just installed v0.4.2 but getting the error `Unable to resolve path to module '@react-native-community/checkbox'`
> > Import works fine, but I cannot get autocompletion for this components' props.
> 
> Have you ever tried to restart your IDE?

I also have this "Unable to resolve" error in VSCode, tried to restart IDE but error remains. Using 0.4.2

**Comment by nicholaslee119** [comment]
Sorry for the delay, 0.5.2 was just released to fix this bug

**Comment by flo5324** [comment]
Just installed v0.5.3
Typings seems ok, but I still get the error "Unable to resolve path to module '@react-native-community/checkbox'"
I tried to delete node_modules and clear intellij's cache/restart

**Comment by studentenfutter1** [comment]
Having the same problem. Everything installed but error Module not found: Can't resolve '@react-native-community/checkbox' still persists.

**Comment by mulssoni** [comment]
"@react-native-community/checkbox": "^0.5.6"
And I'm getting the error with Typescript...

**Comment by JonasWho** [comment]
I'm also getting this error with Flow

"@react-native-community/checkbox": "^0.5.6"

**Comment by maullerz** [comment]
in package.json:
"main": "dist/CheckBox",

in dist dir:
<img width="413" alt="Screenshot 2020-12-18 at 14 19 38" src="https://user-images.githubusercontent.com/5295025/102609467-98a93000-413c-11eb-9158-61e81c0c18aa.png">

obviously, eslint can't handle that situation

**Comment by vlad-glober** [comment]
Does anybody have an update of this?

**Comment by singhvivek2503** [comment]
Any updates?

**Comment by ogard** [comment]
It's still an issue. Any updates?

**Comment by billnbell** [comment]
Wow still issue!

**Comment by billnbell** [comment]
This was never resolved. So here is a solution.

create an index.js in node_modules/@react-native-community/checkbox. Put in it:

```
import CheckBox from './dist/CheckBox';

export CheckBox;
```
Will create a PR.
